const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {execFileSync}=require('node:child_process');
let confirmedPair;
const root=path.resolve(__dirname,'..'),base='http://localhost:8088',coverage=[],checks=[],errors=[];
const env=Object.fromEntries(fs.readFileSync(path.join(root,'.env'),'utf8').split(/\r?\n/).filter(x=>x.includes('=')).map(x=>[x.slice(0,x.indexOf('=')),x.slice(x.indexOf('=')+1)]));
async function request(p,route,body){return p.evaluate(async({route,body})=>{const r=await fetch(ASCLA.api+route,{method:body?'POST':'GET',headers:{'X-WP-Nonce':ASCLA.nonce,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(data.message);return data;},{route,body});}
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'}),context=await browser.newContext({viewport:{width:1366,height:768}});let page;
 try{
  const login=await context.newPage();await login.goto(base+'/wp-login.php');await login.locator('#user_login').fill('demo.prueba@example.invalid');await login.locator('#user_pass').fill(env.ASCLA_PROFILE_DEMO_PASSWORD);await Promise.all([login.waitForNavigation(),login.locator('#wp-submit').click()]);await login.locator('.hero').waitFor();checks.push('Demo profile logs in successfully');
  page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.coverage.startJSCoverage({resetOnNavigation:false});
  const goto=page.goto.bind(page);page.goto=async(...args)=>{coverage.push(...await page.coverage.stopJSCoverage());await page.coverage.startJSCoverage({resetOnNavigation:false});return goto(...args);};
  let release;const held=new Promise(resolve=>release=resolve);await page.route('**/ascla/v1/bootstrap',async route=>{await held;await route.continue();});
  await page.goto(base+'/intranet/',{waitUntil:'domcontentloaded'});assert.equal(await page.locator('.ascla-sidebar').count(),1);assert.equal(await page.locator('.header-brand img').count(),1);
  await page.evaluate(()=>window.kept={sidebar:document.querySelector('.ascla-sidebar'),header:document.querySelector('.ascla-header'),logo:document.querySelector('.brand img'),origin:performance.timeOrigin});
  await page.screenshot({path:path.join(root,'test-results/navigation-initial-loading.png')});release();await page.locator('.hero').waitFor();await page.unroute('**/ascla/v1/bootstrap');
  const stable=async()=>assert.equal(await page.evaluate(()=>window.kept.sidebar===document.querySelector('.ascla-sidebar')&&window.kept.header===document.querySelector('.ascla-header')&&window.kept.logo===document.querySelector('.brand img')&&window.kept.origin===performance.timeOrigin),true);
  await stable();checks.push('Server shell and transparent logo exist before bootstrap and are retained after startup');
  const pages=await page.evaluate(()=>ASCLA.pages),heads={},docs=[],assets=[];
  page.on('request',r=>{if(r.isNavigationRequest()&&r.resourceType()==='document'&&r.frame()===page.mainFrame())docs.push(r.url());if(/ascla-core\/assets\/.*\.(js|css|png)(\?|$)/.test(r.url()))assets.push(r.url());});
  async function go(key){await page.locator('.ascla-sidebar .nav-link[href="'+pages[key].url+'"]').click();await page.locator('#page-content h1').waitFor();assert.equal(new URL(page.url()).pathname,new URL(pages[key].url).pathname);await stable();assert.equal(await page.locator('.ascla-sidebar a[aria-current=page]').getAttribute('href'),pages[key].url);heads[key]=await page.locator('#page-content h1').innerText();if(page.viewportSize().width<760)await page.waitForFunction(()=>document.querySelector('.ascla-sidebar').getBoundingClientRect().right<=1);}
  for(const key of Object.keys(pages))await go(key);assert.deepEqual(docs,[]);assert.deepEqual(assets,[]);checks.push('All 12 routes change URL, active menu and view without document/CSS/JS/logo requests');
  await page.route('**/ascla/v1/**',async route=>{if(route.request().method()==='GET')await new Promise(r=>setTimeout(r,300));await route.continue().catch(()=>{});});
  const rapid=['perfil','eventos','hub','directorio','foros','mensajeria','aliados','galeria','contacto','intranet'];
  await page.evaluate(keys=>{window.shellFailures=[];const check=()=>{for(const e of [kept.sidebar,kept.header,kept.logo])if(!e.isConnected||getComputedStyle(e).visibility==='hidden')shellFailures.push('lost');};window.observer=new MutationObserver(check);observer.observe(document.getElementById('ascla-root'),{childList:true,subtree:true});for(const k of keys)document.querySelector('.ascla-sidebar a[href="'+ASCLA.pages[k].url+'"]').click();},rapid);
  await page.locator('.hero').waitFor();await page.unroute('**/ascla/v1/**');await stable();assert.deepEqual(await page.evaluate(()=>{observer.disconnect();return shellFailures}),[]);assert.equal(await page.locator('#page-content h1').innerText(),heads.intranet);checks.push('Ten rapid clicks with delayed responses keep the shell and finish on the latest view');
  for(const key of ['perfil','directorio','hub','mensajeria','intranet'])await go(key);
  await page.goBack();await page.locator('#page-content h1').filter({hasText:heads.mensajeria}).waitFor();await stable();await page.goForward();await page.locator('.hero').waitFor();await stable();checks.push('Requested route chain plus Back and Forward preserve the document and view');
  await go('perfil');const originalFirst=await page.locator('[name=first_name]').inputValue();await page.locator('[name=first_name]').fill(originalFirst+' cambio temporal');
  await page.locator('.ascla-sidebar .nav-link[href="'+pages.directorio.url+'"]').click();await page.locator('.modal [data-action="unsaved-stay"]').waitFor();assert.equal(new URL(page.url()).pathname,new URL(pages.perfil.url).pathname);await page.locator('.modal [data-action="unsaved-stay"]').click();await page.locator('.modal').waitFor({state:'detached'});
  await page.locator('.ascla-sidebar .nav-link[href="'+pages.directorio.url+'"]').click();await page.locator('.modal [data-action="unsaved-discard"]').waitFor();await page.locator('.modal [data-action="unsaved-discard"]').click();await page.locator('#page-content h1').filter({hasText:heads.directorio}).waitFor();checks.push('Profile warns before internal navigation and supports keep editing or discard changes');
  await go('perfil');const originalBio=await page.locator('[name=bio]').inputValue();const saveLeaveValue='Prueba guardar y salir '+Date.now();await page.locator('[name=bio]').fill(saveLeaveValue);await page.locator('.ascla-sidebar .nav-link[href="'+pages.directorio.url+'"]').click();await page.locator('.modal [data-action="unsaved-save"]').waitFor();await Promise.all([page.waitForResponse(r=>r.url().endsWith('/profiles/me')&&r.request().method()==='POST'),page.locator('.modal [data-action="unsaved-save"]').click()]);await page.locator('#page-content h1').filter({hasText:heads.directorio}).waitFor();await go('perfil');assert.equal(await page.locator('[name=bio]').inputValue(),saveLeaveValue);await request(page,'profiles/me',{bio:originalBio});checks.push('Profile unsaved dialog can save changes and continue to the requested page');
  await go('perfil');const originalCity=await page.locator('[name=city]').inputValue();let saves=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/profiles/me'))saves++;});
  await page.locator('[name=city]').fill('Lima · prueba de navegación');await Promise.all([page.waitForResponse(r=>r.url().endsWith('/profiles/me')&&r.request().method()==='POST'),page.locator('[data-form=profile] button:not([type])').click()]);await page.getByText('Perfil actualizado.',{exact:true}).waitFor();assert.equal(saves,1);await request(page,'profiles/me',{city:originalCity});checks.push('Profile form works after repeated navigation and sends one POST');
  await go('directorio');const match=await request(page,'matching');assert.ok(match.length>0||match.items?.length>0);const peers=(await request(page,'profiles?q=Alicia')).items;const peer=peers.find(p=>p.name==='Alicia Núñez');assert.ok(peer);
  const me=(await request(page,'bootstrap')).me.id; confirmedPair=JSON.parse(execFileSync('docker',['compose','exec','-T','wordpress','php','/opt/ascla-tests/confirmed-pair-fixture.php'],{input:JSON.stringify({action:'setup',a:me,b:peer.id}),encoding:'utf8'}));
  const result=await request(page,'matching/'+peer.id);assert.ok(result.score>0);await page.locator('[data-action=member][data-id="'+peer.id+'"]').click();await page.locator('.modal [data-action=intro]').click();const intro=page.locator('[data-form=intro] textarea');await intro.fill('Mensaje DEMO para probar navegación y conversación.');const sent=page.waitForResponse(r=>r.url().endsWith('/messages')&&r.request().method()==='POST');await page.locator('[data-form=intro] button:not([type])').click();await sent;await page.locator('.modal').waitFor({state:'detached'});await go('mensajeria');await page.locator('#chat-messages .bubble').filter({hasText:'Mensaje DEMO'}).last().waitFor();await stable();checks.push('Demo profile matching '+result.score+'%, editable intro and one private message without reload');
  await page.locator('[data-action=notifications]').click();await page.locator('.activity-inbox').waitFor();assert.ok(await page.locator('.activity-link').count());await page.locator('.modal [data-action=close]').click();checks.push('Demo profile sees seeded notifications');
  for(const[width,height]of [[1920,1080],[1366,768],[768,1024],[390,844]]){await page.setViewportSize({width,height});for(const key of ['intranet','perfil','directorio','hub','mensajeria']){if(width<760){await page.locator('[data-action=menu]').click();await page.waitForFunction(()=>document.querySelector('.ascla-sidebar.open')?.getBoundingClientRect().x>=-1);}await go(key);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}await page.screenshot({path:path.join(root,`test-results/navigation-${width}.png`)});await stable();}checks.push('Stable responsive navigation at 1920, 1366, tablet and mobile');
  await page.setViewportSize({width:1366,height:768});await go('directorio');coverage.push(...await page.coverage.stopJSCoverage());await page.coverage.startJSCoverage({resetOnNavigation:false});await page.reload();await page.locator('#page-content h1').filter({hasText:heads.directorio}).waitFor();checks.push('Manual reload at /directorio/ works');
  const direct=await context.newPage();await direct.goto(pages.perfil.url);await direct.locator('[data-form=profile]').waitFor();assert.match(await direct.locator('[name=first_name]').inputValue(),/Usuario/);await direct.close();checks.push('Direct /perfil/ in a new tab works');
  const nojs=await browser.newContext({javaScriptEnabled:false,storageState:await context.storageState()}),plain=await nojs.newPage();await plain.goto(pages.intranet.url);await plain.locator('.nav-link[href="'+pages.directorio.url+'"]').click();assert.equal(new URL(plain.url()).pathname,'/directorio/');assert.equal(await plain.locator('.ascla-sidebar').count(),1);await nojs.close();checks.push('Without JavaScript native private WordPress links and the server shell still work');
  for(const fault of ['bootstrap','navigation-script']){
   const fallback=await context.newPage();
   if(fault==='bootstrap')await fallback.route('**/ascla/v1/bootstrap',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'Fallo de prueba controlado'})}));
   else await fallback.route('**/ascla-core/assets/navigation.js?*',r=>r.abort());
   await fallback.goto(pages.intranet.url);await fallback.locator('#page-content .error').waitFor();assert.equal(await fallback.locator('.ascla-sidebar').count(),1);assert.equal(await fallback.locator('.ascla-header').count(),1);
   const origin=await fallback.evaluate(()=>performance.timeOrigin);await Promise.all([fallback.waitForNavigation(),fallback.locator('.ascla-sidebar .nav-link[href="'+pages.directorio.url+'"]').click()]);await fallback.locator('#page-content .error').waitFor();assert.equal(new URL(fallback.url()).pathname,'/directorio/');assert.notEqual(await fallback.evaluate(()=>performance.timeOrigin),origin);await fallback.close();
   checks.push('Native WordPress fallback preserves shell when '+fault+' fails');
  }
  await context.clearCookies();await page.locator('.ascla-sidebar .nav-link[href="'+pages.perfil.url+'"]').click();await page.waitForURL('**/login/**');await page.locator('#user_login').waitFor();checks.push('Expired session during internal navigation returns to dedicated ASCLA login');
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(root,'test-results/navigation.json'),JSON.stringify({version:fs.readFileSync(path.join(root,'wp-content/plugins/ascla-core/ascla-core.php'),'utf8').match(/Version:\s*([\d.]+)/)[1],date:new Date().toISOString(),passed:true,checks,jsErrors:errors,documentsDuringInternalNavigation:0,shellAssetRequestsDuringInternalNavigation:0},null,2));console.log(JSON.stringify({passed:true,checks},null,2));
 }catch(error){if(page){console.error(page.url(),await page.locator('#page-content').innerText().catch(()=>''));await page.screenshot({path:path.join(root,'test-results/navigation-failure.png'),fullPage:true});}throw error;}
 finally{if(confirmedPair)execFileSync('docker',['compose','exec','-T','wordpress','php','/opt/ascla-tests/confirmed-pair-fixture.php'],{input:JSON.stringify({...confirmedPair,action:'cleanup'}),encoding:'utf8'});if(page)coverage.push(...await page.coverage.stopJSCoverage().catch(()=>[]));fs.writeFileSync(path.join(root,'coverage/navigation-v8.json'),JSON.stringify(coverage.filter(c=>c.url.includes('/ascla-core/assets/'))));await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
